### ISSUE TITLE
DoctrinePresenceVerifier not instantiated correctly on laravel console command

### ISSUE THREAD

**Issue by DamoneMX** [mitchellvanw/laravel-doctrine#104]
I am using Laravel 4 and writing some tests for my application, the following is the error that I'm getting: 

```
Catchable Fatal Error: Argument 1 passed to Mitch\LaravelDoctrine\Validation\DoctrinePresenceVerifier::__construct() must implement interface Doctrine\ORM\EntityManagerInterface, string given, called in vendor/mitchellvanw/laravel-doctrine/src/LaravelDoctrineServiceProvider.php on line 82 and defined in vendor/mitchellvanw/laravel-doctrine/src/Validation/DoctrinePresenceVerifier.php line 13
```

When I try to use a Validator, it seems that there's an attempt to instantiate the newly added DoctrinePresenceVerifier and then the error occurs.

However, this only happens when using the console version of the application.  When the same controller method is called when my server is running and I hit the endpoint there's no attempt to instantiate the DoctrinePresenceVerifier so everything works correctly. So this is not affecting my web app, only my test suite.

I believe all these changes pertaining DoctrinePresenceVerifier where added in the last pull request and this didn't happen before. This is my first time reporting an Issue, so let me know if additional information is needed as I did a lot of debugging to understand what was happening.

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
