### ISSUE TITLE
Undefined index: metadata

### ISSUE THREAD

**Issue by Padrio** [mitchellvanw/laravel-doctrine#105]
Hey,

when executing "php artisan" im getting this exception:
Undefined index: metadata

Full Exception (Serialized)
`{"error":{"type":"ErrorException","message":"Undefined index: metadata","file":"\/var\/www\/vendor\/mitchellvanw\/laravel-doctrine\/src\/LaravelDoctrineServiceProvider.php","line":88}}`

A closer look at line 88 tells me: 

``` php
$config = $app['config']['doctrine::doctrine'];
 $metadata = Setup::createAnnotationMetadataConfiguration(
            $config['metadata'],
            $app['config']['app.debug'],
            $config['proxy']['directory'],
            $app[CacheManager::class]->getCache($config['cache_provider']),
            $config['simple_annotations']
        );
```

A print_r($config) says: `Array()`
So lets go go back a bit more and print_r($app['config']):
`
[doctrine::doctrine] => Array
                (
                    [0] => doctrine
                    [1] => doctrine
                    [2] => 
                )
`

Yes, my config does exist in app/config//packages/mitchellcanw/laravel-doctrine/doctrine.php.
Im currently using laravel:4.2.\* and larvel-doctrine:0.6.*

While this isn't working i'm going to use laravel-doctrine:0.5.*

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
