### ISSUE TITLE
php artisan "Call to undefined method [package]"

### ISSUE THREAD

**Issue by jamestrusleroval** [mitchellvanw/laravel-doctrine#109]
After placing the service provider in my providers array, php artisan commands no longer work. Any ideas?

It seems to be the line 29 in the LaravelDoctrineServiceProvider class:

    $this->package('mitchellvanw/laravel-doctrine', 'doctrine', __DIR__ . '/..');

that it fails on

**Comment by jamestrusleroval** [comment]
I now see that the package function no longer exists in Laravel 5.

Laravel 4.2: http://laravel.com/api/4.2/Illuminate/Support/ServiceProvider.html
Laravel 5: http://laravel.com/api/5.0/Illuminate/Support/ServiceProvider.html

**Comment by kirkbushell** [comment]
What version of laravel-doctrine are you using? I believe this issue has already been resolved on the dev branch. laravel-doctrine is not yet L5 supported, but we're almost there.

**Comment by jamestrusleroval** [comment]
Ahhh I see, yes... I'm using Laravel 5... That'd be why!

**Comment by kirkbushell** [comment]
You can start using the master branch if you like as we move towards L5 support.

**Comment by jamestrusleroval** [comment]
Unfortunately still uses the package method... But will stay tuned for your updates :)

**Comment by kirkbushell** [comment]
@jamestrusleroval will close this for now as it is resolved on the laravel 5 dev branch.
