### ISSUE TITLE
Are softDeletes working?

### ISSUE THREAD

**Issue by guiwoda** [mitchellvanw/laravel-doctrine#112]
I had to change the way SoftDeletableListener applies changes to the SoftDeletable entity, because it wasn't setting the deleted_at timestamp and it was actually deleting it!

```php
// All $entity methods used here are required in the SoftDeletable interface
if ($entity instanceof SoftDeletable)
{
	if ($entity->isDeleted())
	{
		continue;
	}

	$entity->markAsDeleted();
	$entityManager->persist($entity);

	$now = $entity->getDeletedAt();

	$unitOfWork->propertyChanged($entity, 'deletedAt', null, $now);
	$unitOfWork->scheduleExtraUpdate(
		$entity,
		[
			'deletedAt' => [null, $now]
		]
	);
}
```

**Comment by kirkbushell** [comment]
You cannot check to see if an entity is an instance of based on traits - you have to use the class_uses() function to do those checks - so your check would be failing, which is why it's not working.

**Comment by guiwoda** [comment]
Yeah, I actually have an interface as well as the Trait.
Anyway, I'll see if I can do a test to verify it.
