### ISSUE TITLE
Laravel 5  ?

### ISSUE THREAD

**Issue by alirezarahmani** [mitchellvanw/laravel-doctrine#118]
@mitchellvanw  is this compatible with Laravel 5?

**Comment by jwpage** [comment]
Not really, no. :frowning:

**Comment by alirezarahmani** [comment]
you can use this https://github.com/atrauzzi/laravel-doctrine

**Comment by jwpage** [comment]
This is a duplicate of #40 (Laravel 5), so this can probably be closed.
