### ISSUE TITLE
support for multiple entity managers

### ISSUE THREAD

**Issue by jaimesangcap** [mitchellvanw/laravel-doctrine#122]
Is this feature already supported?

**Comment by kirkbushell** [comment]
It isn't, no - but why would you want multiple ones (out of curiosity).

**Comment by shabushabu** [comment]
For a multi tenant app where each tenant sits in their own database or schema for example. I'm working on an app right now, where most schemas are the same, but then there are a handful of tenants with completely unique tables. For those you need a separate entity manager each so you can migrate and seed them separately.

**Comment by kirkbushell** [comment]
That use-case makes me shiver for all sorts of reasons. lol

**Comment by shabushabu** [comment]
How so?

**Comment by kirkbushell** [comment]
Multi-tenant applications across multiple databases is imho a lot harder to manage than a single database that manages the requirements. It just makes me feel itchy :P

That's not to say it's not a good use-case for multiple entity managers - certainly it is.

**Comment by shabushabu** [comment]
It's harder, true. Why we switched from MySQL databases to PostgreSQL schemas. The concept is almost the same, but you still get the data separation while keeping things simple for database backups and cross-tenant queries.

**Comment by kirkbushell** [comment]
Yeah I guess you're trading one set of issues for another?

**Comment by shabushabu** [comment]
Not really. It works really well if you set your search_path accordingly to make sure that you always have your global schema in there right after the current tenant schema. Then your queries look first in the tenant schema and if it can't find the table there it looks in the global schema.

**Comment by kirkbushell** [comment]
If it's all in one schema you wouldn't have to do that, hence previous comment ;)

**Comment by shabushabu** [comment]
Yeah, but keeping all that data from different companies in the same schema makes me cringe. I wouldn't want that for mine.

**Comment by kirkbushell** [comment]
Just comes down to good code. Lots of companies do it :)

**Comment by kirkbushell** [comment]
Basecamp runs on a single database, to give you an idea. haha

**Comment by shabushabu** [comment]
Not a good enough reason :) Don't use Basecamp.

**Comment by kirkbushell** [comment]
hahaha. Well if I were to add to that - running a pretty complex SaaS application myself with the firm I work for - and opting for a single database has its architectural challenges, but it makes a number of things a lot simpler. In either case - we've digressed haha

**Comment by Daskul** [comment]
I am practicing DDD and as it suggests, you need to divide your application by bounded context. Then each context should have different entity manager. I cant talk more about it since Im not an expert. Here is one example why we wanna use multiple entity managers https://msdn.microsoft.com/en-us/magazine/jj883952.aspx its a .Net implementation though.

**Comment by kirkbushell** [comment]
@Daskul that's not true at all. Bounded contexts do not necessarily mean a different connection or set of rules. Instead, they set boundaries by which other domains can access each other.

**Comment by Daskul** [comment]
well then I dont have much argument. but how can you map 2 entities from different bounded context to the same database table?

**Comment by FoxxMD** [comment]
@Daskul I'm not sure this fits your needs entirely but I pulled in a [PR](https://github.com/mitchellvanw/laravel-doctrine/pull/55) by @npmarrin that allows for multiple entity managers in my [fork for laravel 5](https://github.com/mitchellvanw/laravel-doctrine/issues/40#issuecomment-83742702)

Your `doctrine.config` file is setup like normal except you use an array of entity managers instead of just one:

```
'entity_managers' = [
    'pgsql' => [
        'connection' => 'pgsql',
        'metadata' => [
            __DIR__.DIRECTORY_SEPARATOR.'Models',
        ],
    ],
    'mysql' => [
        'connection' => 'mysql',
        'metadata' => [
            __DIR__.DIRECTORY_SEPARATOR.'Models',
        ],
    ],
    'sqlite' => [
        'connection' => 'sqlite',
        'metadata' => [
            __DIR__.DIRECTORY_SEPARATOR.'Models',
        ],
    ],
```

and then in code you inject an instance of `ManagerRegistry` instead of `EntityManager` -- and instantiate your EM from `ManagerRegistry`:

```
class Controller
{
    public function __construct(ManagerRegistry $reg)
    {
        parent::__construct();
        $this->_em = $reg->getManager('aDefinedEntityManager'); //leave blank to use the 'default' EM
        $this->repo = $this->_em->getRepository('YourEntity');
    }
    ....
```

or if you prefer to use a facade

```
use RegistryManager;

class Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->_em = RegistryManager::getManager('aDefinedEntityManager'); //leave blank to use the 'default' EM
        $this->repo = $this->_em->getRepository('YourEntity');
    }
    ....
```

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
