### ISSUE TITLE
Register custom types

### ISSUE THREAD

**Issue by MartijnDwars** [mitchellvanw/laravel-doctrine#134]
Doctrine supports adding [custom types](http://doctrine-orm.readthedocs.org/en/latest/cookbook/custom-mapping-types.html), but the laravel-doctrine config does not indicate that this is supported. Is there another way to accomplish this?

If this is indeed not possible, then I won't mind working on this feature and creating a PR. Let me know!

**Comment by shabushabu** [comment]
It's fairly easy. Add the type according to the Doctrine docs to the following event:

```php
\Doctrine\DBAL\Events::postConnect
```

We use an event subscriber for this, like so:

```php
<?php namespace App\Listeners\JsonB;

use Doctrine\Common\EventSubscriber as Subscriber;
use Doctrine\DBAL\Event\ConnectionEventArgs;
use Doctrine\DBAL\Events;
use Doctrine\DBAL\Types\Type as BaseType;

class EventSubscriber implements Subscriber {

    /**
     * @return array
     */
    public function getSubscribedEvents()
    {
        return [
            Events::postConnect,
        ];
    }

    /**
     * @param \Doctrine\DBAL\Event\ConnectionEventArgs $args
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    public function postConnect(ConnectionEventArgs $args)
    {
        BaseType::overrideType(BaseType::JSON_ARRAY, Type::class);
    }
}
```

Then register the subscriber in \App\Providers\EventServiceProvider. Something like this:

```php
    /**
     * Here we make sure that we have a tenant set
     *
     * @return void
     */
    public function register()
    {
        $this->registerDoctrineEvents();
    }

    /**
     * And here we register any Doctrine events
     *
     * @return void
     */
    private function registerDoctrineEvents()
    {
        /** @var \Doctrine\Common\EventManager $eventManager */
        $eventManager = registry()->getConnection()->getEventManager();

        $eventManager->addEventSubscriber(new JsonB\EventSubscriber);
    }
```

**Comment by MartijnDwars** [comment]
How do you access the EventManager? You're using `registry()`, but I guess you wrote this method?

**Comment by shabushabu** [comment]
I'm using a fork that supports multiple entity managers:
https://github.com/FoxxMD/laravel-doctrine

This is the registry function:

```php
/**
 * Get the entity manager registry
 *
 * @return \Doctrine\Common\Persistence\ManagerRegistry
 */
function registry()
{
    return app(\Doctrine\Common\Persistence\ManagerRegistry::class);
}
```

If you're not using the same fork, then you can get the connection straight from the entity manager

```php
$eventManager = EntityManager::getEventManager();
```

**Comment by MartijnDwars** [comment]
Thanks. I'm using the same fork (the l5 dev branch), but the issue was with the order in which I registered the providers. It's working now, many thanks!

This solution is so simple that integrating it into this project is unnecessary. Closing the issue.

**Comment by patrickbrouwers** [comment]
Hey, I just open-sourced my Laravel-Doctrine solution in which adding custom types is as easy as adding them to the config:

https://github.com/patrickbrouwers/Laravel-Doctrine
