### ISSUE TITLE
Packagist dev-master use Laravel 4

### ISSUE THREAD

**Issue by fureszpeter** [mitchellvanw/laravel-doctrine#135]
It this a mistake, that dev-master `0faaca3238afdb7e8e6c239f65cb26f353b51209` points to `master` and not to the `develop` branch? Still use L4 and throws `BadMethodCallException`. `Call to undefined method [package]`

Which version should we use for L5 with composer?

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
