### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by isaackearl** [mitchellvanw/laravel-doctrine#136]
It doesn't seem like there have been any changes for 5+ months, and there are alot of open issues.  I want to use doctrine for a project I'm working on but I'm hoping for an implementation that is still being maintained etc.

**Comment by isaackearl** [comment]
is this package going to be updated to work with laravel 5?

**Comment by MartijnDwars** [comment]
A Laravel 5 fork can be found [here](https://github.com/FoxxMD/laravel-doctrine/tree/l5). I started using it a week ago and it works like a charm.

**Comment by josenicomaia** [comment]
@isaackearl I can add one other to the list =]

https://github.com/atrauzzi/laravel-doctrine

**Comment by josenicomaia** [comment]
@MartijnDwars @isaackearl Both FoxxMD and patricjbrouwers joined in this one https://github.com/Laravel-Doctrine/orm

**Comment by MartijnDwars** [comment]
Interesting @josenicomaia, thanks for the update!

**Comment by FoxxMD** [comment]
## For anyone viewing this issue please use [laravel-doctrine/orm](https://github.com/laravel-doctrine/orm) instead!

**We have a much more feature-complete, stable, and up to date integration for Doctrine 2 with Laravel 5+**

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
