### ISSUE TITLE
Override LaravelDoctrine\ORM\Auth\Authenticatable password Doctrine annotation 

### ISSUE THREAD

**Issue by morfin** [mitchellvanw/laravel-doctrine#145]
Hi,

The password annotation defined in the trait does not allow NULL values.
My application needs to allow null. So I tried to simply override the property on my actual User Entity defining there the  annotation I need. The problem is that Doctrine complaints about it:

> [ErrorException]
>  Model\User and LaravelDoctrine\ORM\Auth\Authenticatable define the same property ($password) in the composition of Model\User. This might be incompatible, to improve maintain ability consider using accessor methods in traits instead.

How can I deal with this situation ? I don't want to end up creating my own trait, or even worse, modifying LaravelDoctrine\ORM\Auth\Authenticatable file.

Any idea how to deal with this?

**Comment by kirkbushell** [comment]
Please see: https://github.com/laravel-doctrine as this repository is no longer maintained.
