### ISSUE TITLE
Add Seeding/Fixture Support

### ISSUE THREAD

**Issue by oddz** [mitchellvanw/laravel-doctrine#146]
It would be nice to have seeding/fixtures that are compatible with Laravel doctrine. I'm researching options for my own project which lead me to this blog article.

http://culttt.com/2014/06/30/getting-started-doctrine-2-laravel/

In the comments an individual asks about using fixtures with doctrine and author cites these two sources as possibilities.

https://github.com/fzaninotto/Faker#populating-entities-using-an-orm-or-an-odm
https://github.com/doctrine/data-fixtures

Since faker is already included I think a simple approach would be to replace or offer an alternative for the doctrine seeding and factory generation. One of the nice things is that doctrine is already supported by faker unlike Eloquent. 

The second package is nice but I think is a little dated and doesn't integrate quite as nicely with Laravel. However, I also came across this package.

https://github.com/nelmio/alice

Using alice is probably the approach I'm going to take since it seems very powerful. It also always defining fixture data as yaml or php which is nice for the Laravel folks who want to keep everything in php. Alice already has a bridge for many other packages why not Laravel.

Just something to think about. It would would nice to support the entire gamut of Eloquent functionality including the seeding and factories.

**Comment by kirkbushell** [comment]
see: http://www.laraveldoctrine.org/

**Comment by oddz** [comment]
You just posted a link to the Laravel doctrine home page?

**Comment by kirkbushell** [comment]
And now I'll post another one (read the header):

https://github.com/mitchellvanw/laravel-doctrine

**Comment by oddz** [comment]
My bad, wrong repo. That is where I thought I was.

**Comment by kirkbushell** [comment]
hehe it's okay, it's a little bit confusing, I know.
