### ISSUE TITLE
Use \Doctrine\ORM\Configuration for creation of EntityManager and provide hook to modify configurations

### ISSUE THREAD

**Issue by valllabh** [mitchellvanw/laravel-doctrine#15]
Use `\Doctrine\ORM\Configuration` for creation of `EntityManager` and provide hook to modify configurations.
I know configurations can be modified right now through config. file but there is no way to use `addCustomStringFunction` function of `\Doctrine\ORM\Configuration` as we are using simple array for `EM` creation.

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
