### ISSUE TITLE
Version 0.5.0

### ISSUE THREAD

**Issue by mitchellvanw** [mitchellvanw/laravel-doctrine#30]
Hello everybody,

Many people have had requests for this package. Of course I want to built every single one of them. Now, I don't want to keep you out of the loop and that's why I made this update. I'm working on the next version, which is **0.5.0**. This version will contain the following updates:
- Supporting **MySQL, PostgreSQL and SQLite**.
- Supporting **Read / Write Connections**.
- Ability to add **Extensions**
- Supporting **table prefix setting**

These are the main things I'm adding in the upcoming release. I'm also looking into #15 and what the possibilities are here.

I'll most likely have this released in 2 weeks, before October 1st.

I already thinking about version [0.6.0](https://github.com/mitchellvanw/laravel-doctrine/labels/Version%200.6.0) and would like your help with what this will contain. I've created a label named **Version 0.6.0**, so if you have an idea for this version then add this label to your issue.

Thanks

**Comment by nWidart** [comment]
Hi,

Does version 5.0 supports doctrine extensions line planned ? 
If so, how can we use them, as simply requiring the package isn't enough.

Thank you!
