### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by glennjacobs** [mitchellvanw/laravel-doctrine#40]
Laravel 5 has broken compatibility for the UserProvider.

I've fixed it locally, but it will not work with Laravel 4 - how do you want to handle this? Make a branch specifically for Laravel 5?

**Comment by glennjacobs** [comment]
Laravel 5 is going into Beta this week, so does that mean we can start working on compatibility?

**Comment by kirkbushell** [comment]
Yeah we'll get started on it very soon :)

**Comment by darrencraig** [comment]
I've maintained a fork which currently works with a fresh install of Laravel 5, if it helps anyone until Mitchell & Kirk release something official.

Note: There is currently no way to publish a config file using artisan, so you have to manually copy the vendor/mitchellvanw/laravel-doctrine/config/doctrine.php to /config/doctrine.php

https://github.com/darrencraig/laravel-doctrine

In your composer.json file - 

"require": { "mitchellvanw/laravel-doctrine": "dev-develop" },
"repositories": [
    {
        "type": "vcs",
	     "url": "https://github.com/darrencraig/laravel-doctrine"
    }
]

Good luck :)

**Comment by winkbrace** [comment]
Thanks!

**Comment by kirkbushell** [comment]
Config publishing has now been resolved, and can be found on the docs: http://laravel.com/docs/master/packages#configuration

We're 1 step closer to getting an L5 branch ready :)

**Comment by rcbytes** [comment]
Cool. Now L5 is out, hope you guys release the compatibility branch soon, thanks :smiley:

**Comment by rreynier** [comment]
:+1:

**Comment by mikibrv** [comment]
Any news regarding Laravel 5 compatibility?

**Comment by ldebrouwer** [comment]
I'm able to help testing any Laravel 5 compatible work today and tomorrow.

**Comment by ArthurGuy** [comment]
+1 Looking forward to this

**Comment by DaHaiz** [comment]
push push push :) :+1:

**Comment by ommartin** [comment]
:+1: Any ETA on L5 compatibility?

**Comment by dannykopping** [comment]
:+1: bump

**Comment by FoxxMD** [comment]
Hello all,

[I needed functionality with L5 so I pulled a bunch of the existing PRs into my own fork.](https://github.com/FoxxMD/laravel-doctrine/tree/l5) My build is currently working with Laravel 5 (I'm using it now) but **YMMV**!
* #100 - Fixes for native auth functionality
* #102 - Loading correct contracts for `UserProvider`
* #106 - (Same as #102 ish)
* #110 - Missing use statement
* #113 - Fixed service provider for l5 compatibility
* #117 - (Same as #106 ish and #102 ish)

Non L5 enhancements
* #55 - Allows for multiple entity managers so you can use different db connections

I've included fixes for various parts of all of the above as well (some problems with hash contracts).

To use my fork you can modify your `composer.json` file to include these changes:
```
	"require": {
      "mitchellvanw/laravel-doctrine": "dev-l5",
      "doctrine/orm": "2.5.*"
	},
  "repositories":
  [
    {
      "type": "vcs",
      "url": "https://github.com/FoxxMD/laravel-doctrine"
    }
  ],
 "minimum-stability": "dev" //optionally use this if composer won't play nicely
```

**Comment by rcbytes** [comment]
Hey @FoxxMD , sweet, will test it soon :+1:

**Comment by nloding** [comment]
@FoxxMD - been using your fork all day, works brilliantly so far! Here's hoping an official L5 release of laravel-doctrine is around the corner.

**Comment by alirezarahmani** [comment]
@FoxxMD  use this https://github.com/atrauzzi/laravel-doctrine

**Comment by FoxxMD** [comment]
**All:** I also have another branch of my L5 branch [that implements **YAML** metadata configuration instead of annotations](https://github.com/FoxxMD/laravel-doctrine/tree/l5-yaml).

@nloding Glad it's working for you! :+1: 

@alirezarahmani I actually looked at that project when I was initially researching doctrine integration but there is a lack of documentation and no list of included features. @mitchellvanw has both of those and a larger support community (I couldn't have created a L5 fork without all the PRs people have submitted already!)

**Comment by ninthspace** [comment]
@FoxxMD: your fork works great for me too, thank you!

**Comment by kirkbushell** [comment]
Hey all, little update - am currently chasing up @mitchellvanw about this as I have a part to play as well (finalising and testing). I believe he's quite busy atm as he's been unresponsive the past week or so, but we'll get around to it.

Until then, I do recommend using the forks and support others have written for now. Hopefully we'll have something up soon :)

**Comment by rreynier** [comment]
Any update on an official release?

**Comment by shabushabu** [comment]
I'm gonna need some extra functionality pretty soon. Am happy to do pull requests for those, but a little update on the state of the project would be nice before I invest some time only to find out that it isn't going anywhere. Cheers!

**Comment by FoxxMD** [comment]
**All:** I've added [**cache:clear-***](https://github.com/FoxxMD/laravel-doctrine/commit/2a6491e189698b3eef6d487e5b478f93554428c6) commands to artisan in [my laravel 5 branch](https://github.com/mitchellvanw/laravel-doctrine/issues/40#issuecomment-83742702) for both annotations and yaml branches just FYI.

**Comment by pwm** [comment]
Thanks FoxxMD, will check it out. Any update on the official?

**Comment by FoxxMD** [comment]
All,

Thanks to the @evopix I have added some more very useful functionality to [**my laravel 5 fork**](https://github.com/FoxxMD/laravel-doctrine/tree/l5). 
([Original comment and full setup above](https://github.com/mitchellvanw/laravel-doctrine/issues/40#issuecomment-83742702))

**What's new:**

* [Support for standard and simple drivers (XML, YAML, or annotations)](https://github.com/FoxxMD/laravel-doctrine/pull/3) 
* Prefixes for sqlite config mapping
* [Migrations and mapping conversion console commands](https://github.com/FoxxMD/laravel-doctrine/pull/4)
* Backwards compatibility with all current doctrine configs

If you are using my fork with ANNOTATIONS ONLY **nothing is required of you to take advantage of these changes**, just run `composer update` to get the new functionality!

However if you would like to move to the new config schema (again, not required) the only change you need to make to `doctrine.config` is this:

    'entity_managers' => [
        'default' => [
            ...
            'simple_annotations' => false, //remove this
            'metadata' => [
                'simple' => false //add this
                'driver' => 'annotation' //OPTIONAL, defaults to annotation if not provided
            ],
        ],

If you want to use XML or YAML drivers this is setup inside the `metadata` property of your `entity_manager` array:

    'entity_managers' => [
        'default' => [
            ...
            'metadata' => [
                'simple' => false //instead of simple_annotations,
                'driver' => 'yaml', //or 'xml' or 'annotation'
                'paths' => [base_path('app/Models/mappings')],
                'extension' => '.dcm.yml'
            ],
        ],

As always, @kirkbushell and @mitchellvanw if you'd like to merge in my fork please let me know.

**Comment by rreynier** [comment]
Thanks @FoxxMD, I hope this ends up being merged soon!

**Comment by rcbytes** [comment]
@FoxxMD Matt, you should update your readme :+1:

**Comment by FoxxMD** [comment]
@rcbytes [Updated the readme!](https://github.com/FoxxMD/laravel-doctrine) It now includes all information I've provided in this thread.

**Comment by jurosh** [comment]
Hi guys are you planning to merge changes? There is also possibility to split from @mitchellvanw branch if he is not maintaining it anymore...

**Comment by npmarrin** [comment]
I hate stomping on @mitchellvanw project but if we don't see any traction I would treat @FoxxMD project as the current maintained fork.

**Comment by josenicomaia** [comment]
+1

**Comment by FoxxMD** [comment]
I've added support for [DoctrineExtensions](https://github.com/beberlei/DoctrineExtensions). Check the [readme](https://github.com/FoxxMD/laravel-doctrine/tree/l5#using-doctrineextensions) for details on installation and configuration.

**Comment by josenicomaia** [comment]
I am using https://github.com/atrauzzi/laravel-doctrine

**Comment by FoxxMD** [comment]
## For anyone viewing this issue please use [laravel-doctrine/orm](https://github.com/laravel-doctrine/orm) instead!

**We have a much more feature-complete, stable, and up to date integration for Doctrine 2 with Laravel 5+**

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
