### ISSUE TITLE
YAML Metadata

### ISSUE THREAD

**Issue by hendore** [mitchellvanw/laravel-doctrine#42]
Would adding YAML support just be a case of modifying the service provider line 83 to get a value from the config file and either call

```
$metadata = Setup::createAnnotationMetadataConfiguration(...);
```

or

```
$metadata = Setup::createYAMLMetadataConfiguration(...);
```

Based on the value, or is would there be more involved?

**Comment by FoxxMD** [comment]
How would I go about adding yaml? I don't care about it being supported as long as it works in my build. Is @hendore's approach right?
