### ISSUE TITLE
Doctrine Commandline Tools

### ISSUE THREAD

**Issue by matiux** [mitchellvanw/laravel-doctrine#43]
Hi,
I tried to use Commandline Tools. According to official guide, I can use this command to generate getters and setters:

php/vendor/doctrine orm:generate-entities

but I get this error:

You are missing a "cli-config.php" or "config/cli-config.php" file in your
project, which is required to get the Doctrine Console working. You can use the
following sample as a template:

<?php
use Doctrine\ORM\Tools\Console\ConsoleRunner;

// replace with file to your own project bootstrap
require_once 'bootstrap.php';

// replace with mechanism to retrieve EntityManager in your app
$entityManager = GetEntityManager();

return ConsoleRunner::createHelperSet($entityManager);

So I tried to create the cli-config.php but where is the correct bootstrap.php file?

if I understand correctly, the bootstrap.php file is needed to load EntityManager in cli. It contain the user credential to database access:

http://doctrine-orm.readthedocs.org/en/latest/reference/configuration.html

Thanks

**Comment by zhouyixiang** [comment]
@dannykopping's code integrates with laravel-doctrine better, however, I found this setup didn't allow me run doctrine reverse engineering commands with error "No Metadata Classes to process". 

Steps:

1. convert mapping. This step worked well and all xml files were generated under app/models.
``` bash
php vendor/doctrine/orm/bin/doctrine orm:convert-mapping --from-database xml app/models
```

2. generate entities. This step raised error "No Metadata Classes to process".
``` bash
php vendor/doctrine/orm/bin/doctrine orm:generate-entities --generate-annotations=true --generate-methods=true app/models
```

After searching, I know should set xml metadata driver but there's no configuration entry in laravel-doctrine's config (am I wrong?)

So I updated @matiux's snippet by adding xml driver setup,  below shows the code. Then I could generate entities from database. Hope this may help someone likes me:)

``` php

require_once "vendor/autoload.php";

use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Mapping\Driver\XmlDriver;

$paths = array(__DIR__.'/app/models');
$isDevMode = false;

// the connection configuration
$dbParams = array(
    'driver'   => 'pdo_mysql',
    'user'     => 'homestead',
    'password' => 'secret',
    'dbname'   => 'xxxx',
    'host' => 'localhost:33060'
);
$config = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode, null, null, false);

// setup xml driver
$driver = new XmlDriver($paths);
$config->setMetadataDriverImpl($driver);

$entityManager = EntityManager::create($dbParams, $config);
return ConsoleRunner::createHelperSet($entityManager);
```

**Comment by matiux** [comment]
@zhouyixiang, I added your xml driver implementation in my snippet. So, after some previous change, I have only one file (that I have named cli-config.php) put into the root (at the same level of app) that contains this code:

```php
<?php

require __DIR__.'/bootstrap/autoload.php';

use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Mapping\Driver\XmlDriver;

$paths          = array(__DIR__.'/app/models');
$isDevMode      = Config::get('app.debug'); //false
$app =          require_once __DIR__.'/bootstrap/start.php';
$mysqlData      = Config::get('database.connections.mysql');

$app->setRequestForConsoleEnvironment();

$dbParams       = array(

    'driver'        => 'pdo_'.$mysqlData['driver'],
    'user'          => $mysqlData['username'],
    'password'      => $mysqlData['password'],
    'dbname'        => $mysqlData['database'],
    'charset'       => 'utf8',
    'driverOptions' => [1002=>'SET NAMES utf8'], //1002 is the integer value of PDO::MYSQL_ATTR_INIT_COMMAND
);

// setup xml driver
$driver             = new XmlDriver($paths);
$config             = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode, null, null, false);

$config->setMetadataDriverImpl($driver);

$entityManager      = EntityManager::create($dbParams, $config);

$app->shutdown();

return ConsoleRunner::createHelperSet($entityManager);

```

**Comment by dannykopping** [comment]
For Laravel 5:

```php
<?php
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Illuminate\Foundation\Application;

require __DIR__.'/bootstrap/autoload.php';

/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make('Illuminate\Contracts\Console\Kernel');

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$entityManager = $app->make(EntityManagerInterface::class);
return ConsoleRunner::createHelperSet($entityManager);
```

**Comment by FoxxMD** [comment]
Thanks @dannykopping :+1:

**Comment by sebastiandedeyne** [comment]
Out of curiosity, is there a reason why the commands have to be ported, and we can't just proxy them through to a doctrine cli application?

(ex. `$ php artisan doctrine orm:schema-tool:update --force`)

**Comment by devnix** [comment]
Yes **please**, I'm going crazy trying to use Doctrine 2 on Laravel 5 D:

**Comment by FoxxMD** [comment]
@DevNIX You should consider switching to [laravel-doctrine/orm](https://github.com/laravel-doctrine/orm).

**Comment by mitchellvanw** [comment]
Yea, you should switch @DevNIX. I'm not maintaining this package anymore, because I don't think there's a need nor reason for such a package. The bootstrap of Doctrine 2 is insanely easy and then you'll have all the freedom you need.
