### ISSUE TITLE
Laravel Reminders / Forgotten Password

### ISSUE THREAD

**Issue by jonesio** [mitchellvanw/laravel-doctrine#44]
See: http://laravel.com/docs/master/security#password-reminders-and-reset

The default implementation of Illuminate\Auth\Reminders\ReminderServiceProvider makes a new database connection via DatabaseManager/ConnectionFactory rather than using Doctrine.

**Comment by jonesio** [comment]
Excellent work @neon64! Will take a look!

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
