### ISSUE TITLE
IDEA: Can we defer laravel-doctrine booting until needed?

### ISSUE THREAD

**Issue by kirkbushell** [mitchellvanw/laravel-doctrine#47]
I'm finding that with artisan commands, I generally don't need a database connection until I run a query or anything else of that nature. Is it possible we can somehow lazy-load the database connection and configuration until it's actually required?

**Comment by frankdejonge** [comment]
A big +1 from me. This lead to some weird issues in my case.

**Comment by kirkbushell** [comment]
This is much easier in Laravel 5, so it'll be deferred by default :)

Didn't realise this was still open. haha

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
