### ISSUE TITLE
Custom Repository extending EntityRepository

### ISSUE THREAD

**Issue by jonesio** [mitchellvanw/laravel-doctrine#50]
Hi guys,

Disclaimer: I'm trying this on my version of Laravel 5 (yes I know it's not even beta). Please can someone confirm if this is or isn't the case on L4?

I have an Entity with a custom Repository. That custom repository class is extending the default Doctrine\ORM\EntityRepository.

When trying to use the entity in my app I immediately get the following error:

Unresolvable dependency resolving [Parameter #0 [ <required> $em ]] in class Doctrine\ORM\EntityRepository

The cause seems to be that the $em argument in the EntityRepository constructor is not type hinted. Fixing this first case only leads to further unresolvable dependency issues with other non type-hinted params throughout the initialisation of EntityRepository so not workable (plus I'm hacking at the core Doctrine code).

Now, how best to get around this problem? Is my only option to manually bind each custom repository in the IOC?

Thanks

**Comment by mitchellvanw** [comment]
Unless you bind a repository interface through the IoC container and in the binding use the Entity Manager to get the repository it's not going to work. You can simply inject the custom repository class, since it needs dependencies. I do this:

```php
interface UserRepository {

    public function getAll();
}

class DoctrineUserRepository extends EntityRepository implements UserRepository {

    // stuff...
}
```

Now create a service provider in which you bind the interface:

```php

$this->app->bind(UserRepository::class, function($app) {
    $entityManager = $app[EntityManagerInterface::class];
    return $entityManager->getRepository('User');
});
```

Now you can typehint the interface in your classes.

**Comment by Mircea-Ciuchea** [comment]
I don't know if is the best approach.
```
/** base repository */
use App\Interfaces\RepositoryInterface;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

abstract class Repository extends EntityRepository implements RepositoryInterface
{
    public function __construct(EntityManager $entityManager)
    {
        $metadata = new ClassMetadata($this->entity());
        parent::__construct($entityManager, $metadata);
    }

    abstract function entity();

    public function createEntity(array $data)
    {
        $entity = new $this->_entityName;
        foreach ($data as $field => $value) {
            $methodName = 'set' . ucfirst($field);
            if (!method_exists($entity, $methodName)) {               
                throw new RepositoryException('worng!');
            }
            $entity->$methodName($value);
        }
        $this->save($entity);

        return $entity;
    }

    protected function save($entity) {
       
        $this->_em->persist($entity);
        $this->_em->flush();
    }
}

/** subclass repo */

use App\Repositories\Repository;

class UserRepository extends Repository
{
    function entity() {
        return 'App\Entities\User';
    }
}

/** controller */
use App\Http\Controllers\Controller;
use App\Http\Requests\Auth\PostRegisterRequest;
use App\Repositories\UserRepository;

class RegisterController extends Controller
{
    public function index()
    {
        return view('auth.register');
    }

    public function store(PostRegisterRequest $request, UserRepository $userRepo)
    {
        if ($userRepo->createEntity($request->except('password_confirmation'))) 
            return  redirect('login');
    }
}
```
This worked for me. Hope it helps!

**Comment by Jadro007** [comment]
@Mircea-Ciuchea thanks for your solution, I like it. But it is annoying to implement entity function in each sub-repository class. I use convention that repository is in /repo/ folder and entity in /entity/ folder, for example
/repo/UserRepo.php
/entity/User.php

So I implemented entity function in the base repository like this:

```
public function entity() {
        $className = get_class($this);
        $splitted = explode('\\', $className);
        $splitted[count($splitted) - 2] = "Entity";
        $splitted[count($splitted) - 1] = str_replace("Repo", "", $splitted[count($splitted) - 1]);
        return join('\\', $splitted);
    }
```
