### ISSUE TITLE
Soft delete cascade

### ISSUE THREAD

**Issue by matiux** [mitchellvanw/laravel-doctrine#52]
Hi guys and sorry for my bad English.
I have create 2 entities, user and user_data, binded between them to "user_data_id" in user model.
This is the code in user model:

<pre>
/**
 * @ORM\Entity
 * @ORM\Table(name="user", options={"collate"="utf8_general_ci", "charset"="utf8", "engine"="InnoDB"})
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface {
    use Timestamps;
    use SoftDeletes;
....
    /**
     * @ORM\ManyToOne(targetEntity="UserData", inversedBy="user")
     * @ORM\JoinColumn(name="user_data_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $user_data;
...
</pre>

And this is the code in user user_data model:

<pre>
/**
 * @ORM\Entity
 * @ORM\Table(name="user_data", options={"collate"="utf8_general_ci", "charset"="utf8", "engine"="InnoDB"})
 * @ORM\HasLifecycleCallbacks()
 */
class UserData {

    use Timestamps;
    use SoftDeletes;

    public function __construct() {

        $this->users = new ArrayCollection();
    }
...
</pre>

So, when I delete a record in user_data table from phpmyadmin, the related records in user table will be deleted. But when I perform deleting from code, "soft delete" method, updates the deleted_at column fine, but not also in related tables:

<pre>
        $userDataRepo = $this->em->getRepository('UserData');
        $userData = $userDataRepo->findOneById(1);

        $this->em->remove($userData);
        $this->em->flush();
</pre>

Some suggestion?

**Comment by interludic** [comment]
So no cascading with soft deletes?

**Comment by kirkbushell** [comment]
@interludic this project is no longer maintained.
