### ISSUE TITLE
Add In Support For Doctrine Extensions

### ISSUE THREAD

**Issue by yooper** [mitchellvanw/laravel-doctrine#59]
Hello,

Thanks for developing this package. It would be nice to add in support for Doctrine Extension into this package. I was thinking the main composer file would add in the Doctrine Extensions. But the configuration and inclusion would be set via this package's config file.

Example, in the file app/config/packages/mitchellvanw/laravel-doctrine/doctrine.php have a config array

``` php
['extension' => ['\Gedmo\Tree\TreeListener', 'Gedmo\Loggable\LoggableListener' ]]
```

**Comment by zhouyixiang** [comment]
@nWidart I have the same issue, have you found the solution?

**Comment by nWidart** [comment]
I've sadly not found a way to make it work.

In the mean time I've made a [trait](https://github.com/AsgardCms/Core/blob/develop/Doctrine/Translatable.php), a refactored version of @freekmurze, that handles the translations of an entity.

It basically lets you do something like the following:

``` php
$category = $this->entityManager->getRepository('Modules\Blog\Entities\Category')->find(1);
$post = new Post();
$post->createOrUpdateTranslation('title', 'en', 'Title en');
$post->createOrUpdateTranslation('title', 'fr', 'Titre fr');
$post->setCategory($category);

$this->entityManager->persist($post);
$this->entityManager->flush();
```

And to read a translation, simple access the property like usual:

``` php
$post->title
```

This solution isn't as clean as the Doctrine Extensions, but hopefully someone figures out how to use them inside Laravel with this package.

**Comment by guiwoda** [comment]
+1 to this, I think it needs a more flexible EM binding. Maybe pre- and post- EM created events to hook up extensions?

**Comment by patrickbrouwers** [comment]
I got it working using:

```php
        $entityManager = $this->app['Doctrine\ORM\EntityManager'];
        $eventManager = $entityManager->getEventManager();
        $reader = $entityManager->getConfiguration()->getMetadataDriverImpl()-    >getReader();

        DoctrineExtensions::registerAbstractMappingIntoDriverChainORM(
            new MappingDriverChain(),
            $reader
        );

        $sluggableListener = new SluggableListener();
        $sluggableListener->setAnnotationReader($reader);
        $eventManager->addEventSubscriber($sluggableListener);

        $sortableListener = new SortableListener;
        $sortableListener->setAnnotationReader($reader);
        $eventManager->addEventSubscriber($sortableListener);
``

**Comment by msdm** [comment]
The code provided by @patrickbrouwers above works fine for the annotations but it does not create the database tables needed for some of extensions eg. Loggable and Translatable. The following code fixes this issue.

    $entityManager = $this->app['Doctrine\ORM\EntityManager'];
    $eventManager = $entityManager->getEventManager();
    $reader = $entityManager->getConfiguration()->getMetadataDriverImpl()->getReader();
    $driverChain = new MappingDriverChain();

    DoctrineExtensions::registerMappingIntoDriverChainORM($driverChain, $reader);
    
    $driverChain->addDriver($entityManager->getConfiguration()->getMetadataDriverImpl(), 'App');
    $entityManager->getConfiguration()->setMetadataDriverImpl($driverChain);

    $loggableListener = new LoggableListener();
    $loggableListener->setAnnotationReader($reader);
    $eventManager->addEventSubscriber($loggableListener);

**Comment by patrickbrouwers** [comment]
Nice inprovement. Didn't try those onces yet.

**Comment by patrickbrouwers** [comment]
In the meantime I have open-sourced my Laravel Doctrine solution, in which enabling DoctrineExtensions is as easy as adding the extension to the config file.

https://github.com/patrickbrouwers/Laravel-Doctrine

**Comment by torniker** [comment]
+1

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
