### ISSUE TITLE
Class auth does not exist

### ISSUE THREAD

**Issue by paolooo** [mitchellvanw/laravel-doctrine#71]
I'm using:

```
    "laravel/framework": "4.2.*",
    "codesleeve/asset-pipeline": "dev-master",
    "rhumsaa/uuid": "*",
    "doctrine/orm": "2.5.*",
    "symfony/yaml": "3.*",
    "mitchellvanw/laravel-doctrine": "0.5.*"
```

When I run `php artisan`, I got this error.

`{"error":{"type":"ReflectionException","message":"Class auth does not exist","file":"\/bootstrap\/compiled.php","line":235}}`

If I remove this line ( https://github.com/mitchellvanw/laravel-doctrine/blob/master/src/LaravelDoctrineServiceProvider.php#L30 ) it works fine.

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
