### ISSUE TITLE
SQLite driver not supported

### ISSUE THREAD

**Issue by rizqidjamaluddin** [mitchellvanw/laravel-doctrine#77]
The [pdo_sqlite](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#pdo-sqlite) driver doesn't work because the service provider is trying to grab values from nonexistent array keys (which are irrelevant for sqlite). Trying to use an sqlite driver raises `Undefined index: host` from LaravelDoctrineServiceProvider.php:143.

Maybe a simple if/else for now, as sqlite seems to be the odd one out?

**Comment by kirkbushell** [comment]
sqlite was the first driver i supported when writing the configuration update. Did you provide a host in your configuration? Which branch are you running off of? Neither master or develop have line 143 that pertains to such an issue.

**Comment by rizqidjamaluddin** [comment]
I'm on 0.4.3 as per suggested constraints for installation on the readme. The line in question is [this one](https://github.com/mitchellvanw/laravel-doctrine/blob/0.4.3/src/LaravelDoctrineServiceProvider.php#L143), and no, I didn't provide a host in the sqlite configurations because it's not a key in laravel's config, nor is it a key in doctrine's config.

I can try upgrading to 0.5.x and try again, perhaps?

**Comment by kirkbushell** [comment]
Ahhh. Try one of the newer versions/dev. sqlite wasn't property supported back then :)

**Comment by rizqidjamaluddin** [comment]
Is 0.5.x stable enough to use in general? I haven't installed it just yet, but it does look like it'll fix the issue.

**Comment by kirkbushell** [comment]
It should be fine. Quite a few of us are using it in big projects atm, it's just that it's ongoing with lots of extra features/requirements coming.etc, so it can be unstable. Test, if it works - awesome :)

We should wrap it up when L5 is released.

**Comment by rizqidjamaluddin** [comment]
Yep, looks like it. Thanks for the help! :)
