### ISSUE TITLE
Double class definitions when generating schema with files already autoloaded

### ISSUE THREAD

**Issue by rizqidjamaluddin** [mitchellvanw/laravel-doctrine#78]
So doctrine's schema tool is meant to scan certain folders for files to parse as entities, and generate schemas thereof. A problem occurs when using commands such as `php artisan doctrine:schema:create` in an environment where the classes it scans are already loaded, in my case by service provider setups.

For instance, in doctrine.php:

```
    'metadata' => [
        base_path('NS/Users')
    ],
```

If there exists a class `NS\Users\UserServiceProvider`, and it's included in the config service provider listing, this class is initiated by laravel as soon as the app is booted up. When doctrine goes through the files to parse for entities, the service provider is already loaded into PHP and PHP refuses the double declaration:

```
$ php artisan doctrine:schema:update
Checking if database needs updating....
PHP Fatal error:  Cannot redeclare class NS\Users\UserServiceProvider in /NS/Users/UserServiceProvider.php
```

One cheap way to fix this is by moving entities into their own namespace, but this isn't very ideal (I would prefer to just use my namespace root instead of having to specify each subfolder) and isn't foolproof either; sometimes a service provider would autoload an entity as well, e.g. to do `$this->app->bind(SomeEntity::class, ...)`. This would throw the error in any situation as long as the service provider was invoked.

The only real solution would be to execute the schema generation in some way such that other service providers aren't loaded, but this is likely out of the package's control.

Am I missing a different obvious solution somewhere?

**Comment by kirkbushell** [comment]
You should be pointing it to your entities path, not your root of your module/app/namespace.

**Comment by rizqidjamaluddin** [comment]
The problem is that sometimes the entities themselves have been autoloaded (described near the end there), so it doesn't really fix the issue.

**Comment by kirkbushell** [comment]
Stop them from autoloading. Should only load when needed.

**Comment by rizqidjamaluddin** [comment]
They're being referred to for IoC bindings and SP register methods (e.g. instantiating entities for use by other components). I could probably try to fix this by lazy-loading anything that instantiates entities, I'll try that.

Aside from that, I'd prefer to not be forced to put entities into their own namespaces (that is to say, I'd prefer Users\User over Users\Entities\User), though it's an acceptable solution if it's a requirement.

**Comment by kirkbushell** [comment]
You can have them in the same namespace, just don't load them until they're needed.

**Comment by rizqidjamaluddin** [comment]
That's the thing - they're needed in SP register methods, which are run on app boot. That said, setting providers to [deferred](http://laravel.com/docs/4.2/packages#deferred-providers) fixes the problem. Just make sure the `provides` method is up to date.

**Comment by kirkbushell** [comment]
You shouldn't need to define them in SP classes unless you have specific bind work to be done, even then you should be making them deferred and using the provides() method to let laravel know what bindings you're providing via that service provider.

**Comment by kirkbushell** [comment]
The only time you DON'T defer a service provider, is when you need something on every request, or you need to do some special bindings to replace Laravel bindings.etc. such as the translator.

**Comment by rizqidjamaluddin** [comment]
Setting deferred actually didn't work for some reason, but I can't be sure because I didn't test this long enough. For some reason they were still getting executed. Maybe something else invoked them? Not sure. Using closures in bindings worked fine; before this I had a bad habit of instantiating variables in the register method and then returning them in a shared closure, as opposed to instantiating them directly in the closure. The latter works fine, thanks for the heads up.

As a side note, the service provider itself still needs to be away from the entities which the schema tool scans for, because it's getting loaded by laravel. Just in case someone stumbles upon this.

**Comment by kirkbushell** [comment]
You might need to bring that up on the laravel forums, but it should work just fine. Make sure you implement the provides() method for those bindings that are necessary for deferred providers.

Without seeing code (please don't post it here), it's possible you're not using service providers the way they're intended. I could be misunderstanding but it seems as though you're not setting them up correctly. In either case - ti's not a laravel-doctrine issue.

**Comment by rizqidjamaluddin** [comment]
Yes, this part is out of scope. The original question was just about invoking the schema tool outside of the influence out of the other service providers, so the solution to that is just to make sure SPs aren't scanned and to make sure entities aren't instantiated in SP `register` contexts. Thanks for the help, I've got it to work nicely. :)

**Comment by rizqidjamaluddin** [comment]
Okay, I found my actual problem. Schema tool uses `require_once`, so it's not supposed to double-load the same files. It turns out, my PSR-4 autoloading under composer.json was in _lowercase_:

```
        "psr-4": {
            "Acme\\": "acme"
        }
```

While the actual folder was properly uppercased (`Acme`). So composer did an initial load of `Acme\Users\UserServiceProvider` from `/acme/Users/UserServiceProvider` (lowercase because this was what was given in the composer.json file) - which properly resolved. Then the Schema Tool, in its file iteration, tried to `require_once /Acme/Users/UserServiceProvider` - which PHP though it _had not_ loaded, because of the different capitalization. Fixing the line in composer.json to match the real directory capitalization fixed it.

So yea, it was my fault all along, naming the folder incorrectly in the composer.json file.

Let this be a lesson to children and filesystems everywhere.
