### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by matiux** [mitchellvanw/laravel-doctrine#80]
How can I enable query caching?

I have read this page:
http://doctrine-orm.readthedocs.org/en/latest/reference/caching.html#query-cache
that explains how to enable query caching

How can I use this features?

Tanks

**Comment by matiux** [comment]
I enabled the apc cache by editing configuration file package:
~~~
    'cache_provider' => 'apc',
~~~

So, when I execute the query, them are cached, I seen by apc user panel.
Now, how can I use the stored value?
When I execute the query after the first time, I see in the profiler (I use clockwork) that the query are executed again

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
