### ISSUE TITLE
Documentation needs update - Working only with php > 5.5

### ISSUE THREAD

**Issue by klodoma** [mitchellvanw/laravel-doctrine#82]
Hi, 

I get the following error with php 5.4. 

syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

The documentation should specify this aspect. 
The ::class constant is available only in Php 5.5. 

![screenshot_124](https://cloud.githubusercontent.com/assets/944350/5801216/f1de43dc-9fe8-11e4-91cc-f9862c6b142b.png)
![screenshot_123](https://cloud.githubusercontent.com/assets/944350/5801217/f1e20a76-9fe8-11e4-8e24-b25c5c1b0c30.png)

Regards, 
Andrei.

**Comment by mitchellvanw** [comment]
This is correct. This package use `PHP >= 5.5.0`. The requirement is set in the [composer.json](https://github.com/mitchellvanw/laravel-doctrine/blob/master/composer.json#L14).

Thanks, but closing this issue
