### ISSUE TITLE
Crash in SoftDeletableListener

### ISSUE THREAD

**Issue by adamwathan** [mitchellvanw/laravel-doctrine#83]
The call to `class_uses_recursive` here is blowing up for me when using orphan removal:

https://github.com/mitchellvanw/laravel-doctrine/blob/develop/src/EventListeners/SoftDeletableListener.php#L30

`class_uses_recursive` is expecting a fully qualified class name as a string, but an actual entity is being passed in, which blows up when Laravel is trying to use it as a key here:

https://github.com/laravel/framework/blob/master/src/Illuminate/Support/helpers.php#L352

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
