### ISSUE TITLE
 Help with Error creating schemas

### ISSUE THREAD

**Issue by wruizcanal** [mitchellvanw/laravel-doctrine#86]
I think a User entity as in the example of the package and when I run the 'php artisan doctrine: schema: create' command gives me an error and that's not what happens. The error:

C:\xampp\htdocs\laravel>php artisan doctrine:schema:create
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","me
ssage":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRI
NG) or variable (T_VARIABLE) or '{' or '$'","file":"C:\\xampp\\htdocs\\laravel\\
vendor\\mitchellvanw\\laravel-doctrine\\src\\LaravelDoctrineServiceProvider.php"
,"line":58}}

**Comment by wruizcanal** [comment]
When I work on 'www.codio.com' which is a Web-Based IDE if it works without problems but on my pc that does not have internet gives the above error.

**Comment by kirkbushell** [comment]
Could you please highlight the line you're having problems with? I would assume it's the ::class notation, which requires PHP 5.5.

**Comment by wruizcanal** [comment]
Si, estaba trabajando con PHP 5.4. Actualicé a 5.5 y todo fue bien.
Muchas gracias de todas formas.

2015-01-28 13:33 GMT+01:00, Kirk Bushell <notifications@github.com>:

**Comment by wruizcanal** [comment]
Yes, I was working with PHP 5.4. I updated to 5.5 and everything went
well. Thank you very much anyway.

2015-01-29 15:45 GMT+01:00, Walter Alfonso Ruiz Canal <wruizcanal@gmail.com>:
