### ISSUE TITLE
How and where would you register a custom filter like TrashedFilter?

### ISSUE THREAD

**Issue by otherjohn** [mitchellvanw/laravel-doctrine#89]
Hi,
I am creating a filter like the trashedfilter and am trying to register it. But it looks like Laravel is not finding the filter. 
Here is my service provider that registers it;
``` PHP
use Illuminate\Support\ServiceProvider;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Configuration;
use App\Domain\TenantFilter;
class DoctrineServiceProvider extends ServiceProvider
{
    protected $defer = false;
    
    public function register()
    {
        $this->registerMultiTenantFilter();
    }

    protected function registerMultiTenantFilter()
    {
        $config = new Configuration();
        $config->addFilter('tenant',TenantFilter::class);
    }
}
```

I also added this provider to my app.php file.

**Comment by kirkbushell** [comment]
It has to be added to the configuration metadata, I believe. We have a trashed filter in the develop branch which is slated for Laravel 5 (nearly there).

**Comment by mitchellvanw** [comment]
Hi @otherjohn, your code won't work because it's currently not possible to extend the Doctrine Configuration. Monday I'm releasing a new minor version of Laravel Doctrine. This will fix a lot of small bugs and add all the Doctrine CLI commands to Artisan. This update includes Doctrine not loading on `php artisan`.

**Comment by mitchellvanw** [comment]
Here's an [update](https://github.com/mitchellvanw/laravel-doctrine/issues/91) on this package.

**Comment by otherjohn** [comment]
Will the monday update have the extendable configuration or will that come later.

**Comment by mitchellvanw** [comment]
This update will be made later
