### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by mitchellvanw** [mitchellvanw/laravel-doctrine#91]
Hello Everybody, I decided to create this issue to inform all of you on the updates that are coming. Soon I'm releasing version `0.6`. This version will include:
- several bug fixes
- all Doctrine CLI commands in Artisan
- lazy loading Doctrine in Artisan (So it's not loaded on every artisan command you do)

According to Taylor's tweet he'll be releasing `Laravel 5` next week. When the new major version of Laravel is released version `1.0` of this package will be released and support for `Laravel 4` for the Laravel Doctrine package will be moved under the branch `laravel4`. From this point on only bugfixes for Laravel 4 will be supported.

And now the exciting part..

A lot of people have been requesting the ability to extend the Doctrine Configuration, but for us to support all of the Configuration options is not feasible. So we've come up with a solution that will give you the flexibility you need. Shortly after version `1.0` we're going to release **extensions**. In your applications you'll be able to create extension classes and have access to Configuration, Entity Manager, the package config, Event Manager, and Annotation Reader.

We're still looking at finalizing this, but an extension will look something like this:

``` php
class SoftDeleteableExtension implements Extension {

    public static function loadExtension(Configuration $metadata, ExtendedMappingDriverChain $driverChain, CachedReader $cachedAnnotationReader, EntityManager $entityManager, EventManager $eventManager,  $config) {
        $metadata->addFilter('trashed', TrashedFilter::class);
        $eventManager->addEventListener(Events::onFlush, new SoftDeleteableListener);
        $entityManager->getFilters()->enable('trashed');
    }
}
```

Even the Laravel Doctrine package configurations will be extensions. This will make it possible for you to disable the package's extensions and replace them with your own. Because this will break BC it'll be released under version `2.0`.

I'll be tweeting about new versions and updates at [@mitchellvanw](https://twitter.com/mitchellvanw).

Thanks!

**Comment by nWidart** [comment]
Good news :)

Will the [Doctrine Extensions](https://github.com/Atlantic18/DoctrineExtensions) work with this new structure ?

**Comment by mitchellvanw** [comment]
@nWidart No, I've looked at those and decided not to use them, it'll be similar though. It would be far easier to create our own system and not worry about the them. What soon is possible is for others to create extensions and put them on Packagist

**Comment by nWidart** [comment]
Oh that's too bad! Those extensions have -**very-** helpful helpers, like for instance the Translator. Why re-invent the wheel if they already exists?

**Comment by mitchellvanw** [comment]
Some look great and we might make them as well, in our own way. I personally don't like some of the decisions made in that package. I also believe that reinventing the wheel could be a good thing. Even if it's just to look at a problem from a different angle

**Comment by soyuka** [comment]
As long as we can add our own Listeners this seems great!

Will it be possible to unload a specific extension? Assuming I don't want to use `SoftDelete` but I want to keep the `PrefixTable` out of the box?

Thanks for the great work!

**Comment by mitchellvanw** [comment]
Yes, @soyuka. You'll have complete control. The `Proxy` configuration will be an extension as well. What this package will become is a bootstrap for Doctrine with some basic extensions, if you need some logic in whatever happens with the `proxy` config then you just create your own `proxy` extension and use that instead of the default one.

**Comment by soyuka** [comment]
:+1: 

So, as Doctrine Extensions are basically Listeners, they could be implemented by Laravel-Doctrine users.

Proxying commands from artisan through Doctrine directly will be very useful too! Excited about this :).

You'll still keep the TablePrefix and Softdelete extensions in this repo?

**Comment by mitchellvanw** [comment]
Yes, these extensions will remain in this package. Any other extension we add in the future we'll be added to the `core` under proposal otherwise we'll create a separate package

**Comment by fedeisas** [comment]
@mitchellvanw I'm currently migrating a PHP project from another framework into Laravel. It uses Doctrine repositories extensively. I'd love to see something about EntityRepository as discussed on #50.

**Comment by FoxxMD** [comment]
Laravel 5 has been out for over a month now -- when is 1.0 coming? There's a huge amount of pull requests for L5 support that could be very useful...

**Comment by Quagh** [comment]
Any updates? Is this project still actively being maintained?

**Comment by nWidart** [comment]
Doubtful, I use [this forked version on laravel 5](https://github.com/Maatwebsite/laravel-doctrine/tree/develop).

**Comment by ldebrouwer** [comment]
Could the project perhaps be handed over to the community to ensure further development?

**Comment by kirkbushell** [comment]
I believe the community needs something a step further. Laravel-doctrine is a great project, something @mitchellvanw and i have been working on for a while, but alas real life has gotten in the way of maintaining this project the last 3 or 4 months.

I'm working on another project that basically makes doctrine the default implementation for Laravel, rather than Eloquent, which results in a much slimmer, nicer build of Laravel.

**Comment by shabushabu** [comment]
@kirkbushell Sounds interesting. Got a link maybe to check it out?

**Comment by ldebrouwer** [comment]
@kirkbushell Sounds very interesting indeed. If you need additional hands, please let me know.

**Comment by kirkbushell** [comment]
Not yet, as I'm still planning the project out. At it's core, however - will have the laravel-doctrine package, along with laravel.

**Comment by FoxxMD** [comment]
@Quagh @nWidart @ldebrouwer [I've got a fork with a large amount of functionality improvements and l5 compatibility fixes](https://github.com/mitchellvanw/laravel-doctrine/issues/40#issuecomment-83742702) I've been working on for a while. If you'd like to contribute anything else I'm happy to accept PRs

**Comment by FoxxMD** [comment]
## For anyone viewing this issue please use [laravel-doctrine/orm](https://github.com/laravel-doctrine/orm) instead!

**We have a much more feature-complete, stable, and up to date integration for Doctrine 2 with Laravel 5+**

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
