### ISSUE TITLE
Auth Problem

### ISSUE THREAD

**Issue by wruizcanal** [mitchellvanw/laravel-doctrine#96]
Hello:
I have a problem when trying to login. I can create the user using "EntityManager" but when I insert credentials and call the method "Auth :: Attempt (array ('username' => $ username, 'password' => $ password), true)" gives me an error:

Doctrine \ Common \ Persistence \ Mapping \ MappingException
Class '' does not exist

I followed all the steps in the wiki but not what happens.

**Comment by mitchellvanw** [comment]
A couple of questions:
- Have you added the service provider to `app/config/app.php`.
- Could you share you the following code
 - Auth config
 - Code where you're using Auth::attempt()
 - Your User entity

**Comment by wruizcanal** [comment]
This is te proy:
https://my.pcloud.com/publink/show?code=XZG3nkZGtqiNQLzCKbdFOWeUdIbqucIWQPy

**Comment by mitchellvanw** [comment]
Closing because project is no longer maintained. Thanks.
