### ISSUE TITLE
Eloquent-ish models

### ISSUE THREAD

**Issue by fedeisas** [mitchellvanw/laravel-doctrine#97]
I'm currently tweaking this library, and I started to implement some interfaces from Eloquent on my BaseModel, such as Arrayable, Jsonable, ArrayAccess, etc.

Is this something you would consider merging?

Thanks!

**Comment by kirkbushell** [comment]
Probably not - the reason why many of us like Doctrine and its entities, is because they're devoid of any logic other than the business domain that is specific to the entity.
