### ISSUE TITLE
PHP 5.5 seems to be required for develop branch

### ISSUE THREAD

**Issue by minorgod** [mitchellvanw/laravel-doctrine#98]
I was able to install the dev branch on Laravel 5.0, but after enabling the service provider and running composer-update or dump-autoload I was getting an unexpected Class exception on line 56 of "vendor/mitchellvanw/laravel-doctrine/src/LaravelDoctrineServiceProvider.php". Turned out I needed to update my installed php version from 5.4 to 5.5 to get the error to go away. I noticed that in the Dec 4, 2014 commit (f2f8643e8c371d885b179b5227a69421ff4914ff) the composer.json minimum php version requirements were changed from 5.5 to 5.4, so maybe it needs to be changed back to 5.5 in the dev branch?

**Comment by kirkbushell** [comment]
Yeah seems we just need to update composer. Easy done - thanks :)
