### ISSUE TITLE
Clearing cache?

### ISSUE THREAD

**Issue by Padrio** [mitchellvanw/laravel-doctrine#99]
So I deleted a table which was associated with another table, and now doctrine still tries to fetch it.
And now i cant access my application without getting the exception:

`Property User::cookie does not exist`

Surfing aroung i found out that i need to clear my doctrine cache (result // query // metadata) - but you dont have implemented this into atrisan.

Could you maybe implement this commands, too?

**Comment by mitchellvanw** [comment]
@Padrio I'm working on implementing all of the Doctrine Console Commands as we speak. Version `0.6` will be released either today or tomorrow, this will include all of the Doctrine Console Commands. You can test the new version just by requiring the branch "dev-0.6". Right now, it's only possible to clear the query cache. Other will follow later today.

**Comment by Padrio** [comment]
Oh, thats perfect!
But im going to wait for the stable build, since im using the website already in a productive mode.
